baseURL = "http://scawwyhowwowtheatre.com/"
languageCode = "en-us"
title = "Scawwy Howwow Theatre"
theme = "scawwy-howwow"
[params]
    description = ""

[deployment]

[[deployment.targets]]
name="s3"
URL="s3://scawwyhowwowtheatre.com?region=us-east-1"

[menus]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    pre = "<i class='fas fa-home'></i>"
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
    pre = "<i class='fas fa-ghost'></i>"
[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3
    pre = "<i class='fas fa-book-dead'></i>"

[[menu.social]]
    name = "Facebook"
    url = "https://facebook.com/scawwyhowwowtheatre/"
    pre = "<i class='fab fa-facebook'></i>"
[[menu.social]]
    name = "Instagram"
    url = "https://instagram.com/scawwyhowwowtheatre/"
    pre = "<i class='fab fa-instagram'></i>"
[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/unredpod"
    pre = "<i class='fab fa-twitter'></i>"
